import pandas as pd
df=pd.read_csv('zomato.csv')
df.info()
df.drop(['url','address','phone','dish_liked','reviews_list','menu_item','location','rest_type','location','rest_type'],axis=1,inplace=True)
df=df.rename(columns=({'name':'restaurant_name','rate':'rating','approx_cost(for two people)':'cost per person','listed_in(city)':'city','listed_in(type)':'restaurant_type'}))
df=df.dropna(subset=(['cuisines','cost per person']))
df=df.drop_duplicates()
df['rating']=df['rating'].astype(str)
df['rating']=df['rating'].str.replace('/5','')
df['rating']=df['rating'].str.replace('NEW','nan')
df['rating']=df['rating'].str.replace('-','nan')
df['rating']=df['rating'].astype(float)
df['rating']=df['rating'].fillna(df['rating'].mean())
df['rating']=df['rating'].round(2)
df['cost per person']=df['cost per person'].astype(str)
df['cost per person']=df['cost per person'].str.replace(',','')
df['cost per person']=df['cost per person'].astype(int)
df['cost per person']=df['cost per person']/2
df['restaurant_name']=df['restaurant_name'].astype(str)
df['online_order']=df['online_order'].astype(str)
df['book_table']=df['book_table'].astype(str)
df['cuisines']=df['cuisines'].astype(str)
df['restaurant_type']=df['restaurant_type'].astype(str)
df['city']=df['city'].astype(str)
df.to_csv('zomato_clean_data.csv',index=False)
